### ISSUE TITLE
Missing filter value in BrowseSync

### ISSUE THREAD

**Issue by MoshiMoshi0** [plutinosoft/Platinum#14]
There is a missing filter value: "upnp:originalTrackNumber" in PltSyncMediaBrowser::BrowseSync [definition](https://github.com/plutinosoft/Platinum/blob/master/Source/Devices/MediaServer/PltSyncMediaBrowser.h#L121).

**Comment by c0diq** [comment]
This is the default value, you can specify what you want when you invoke it.

**Comment by MoshiMoshi0** [comment]
Well, the method is protected so I cant. Also the default filter value is different than in PLT_MediaBrowser::Browse, adding that would keep it consistent.

**Comment by c0diq** [comment]
There are two PltSyncMediaBrowser::BrowseSync, the one that is public lets you specify the filter you want. Why do you need access to the protected one?
