### ISSUE TITLE
False URL created by Device.getAbsolutePath(String path)

### ISSUE THREAD

**Issue by axen1314** [plutinosoft/Platinum#17]
I tried to get an action by using these:
`
Service service = device.getService("urn:schemas-upnp-org:device:MediaRenderer:1");
Action action = service.getAction("SetAVTransportURI");
`
Then I found "service" is created but "action" is null. I checked the source code and confirmed it caused by these:

`
// Service.java
private Node getSCPDNode() {
    try {
			
        URL scpdUrl = new URL(rootDev.getAbsoluteURL(scpdURLStr));
			
        scpdNode = getSCPDNode(scpdUrl);		
			
        if (scpdNode != null) {
				
           data.setSCPDNode(scpdNode);
				
           return scpdNode;
			
       }
		
    }
    ...
}
`
it got a false URL by using rootDev.getAbsoluteURL(scpdURLStr), this is what I got:
![image](https://user-images.githubusercontent.com/25617051/47250127-2dc21880-d44f-11e8-9155-d958a172742d.png)
Is is a bug?

**Comment by c0diq** [comment]
I think you’re mistaken about which SDK. Looks like you’re using Cyber (java)

-s

**Comment by axen1314** [comment]
Oh，yes！Sorry，I made a mistake! Thanks for you reply very much.

**Comment by axen1314** [comment]
Oh，yes！Sorry，I made a mistake! Thanks for you reply very much.
