### ISSUE TITLE
It's not stable when I used it in my iOS app..

### ISSUE THREAD

**Issue by fuCking-Life** [plutinosoft/Platinum#20]
Hi. I have some trouble when I used Platinum in my iOS app.
I feel it's not stable.
In my app, I have a list to present all devices  which have  'AVTransport' service. These devices seem as DMR. But,the list of devices will be refreshed in several seconds because of  receive list change notification.  Some methods are called frequently, such as "PLT_::OnMRRemoved","PLT_::OnMRAdded"..I don't know what happend.
After that,i suspected network environment.So, I changed network . But it's no help...
Can you replay me when you see this issue?
Thanks for your contribution.

**Comment by c0diq** [comment]
There's no throttling on when a device is added or removed so if a device is misbehaving, you should add a throttle mechanism to update your list only every N seconds with a buffer. 
Can you identify which device is causing this behavior and post it here please?
