### ISSUE TITLE
how to use MicroMediaController?

### ISSUE THREAD

**Issue by ShiverZm** [plutinosoft/Platinum#34]
the usage of MicroMediaController,some thing like command order

**Comment by c0diq** [comment]
The [README](https://github.com/plutinosoft/Platinum/blob/master/README.md#micromediacontroller)explains the commands. `setms` to specify the media server, then `setmr` to specify the media renderer. Once Media Renderer is set, you can open/play/stop by specifying a media item from the selected media server.
