### ISSUE TITLE
Crash sometimes

### ISSUE THREAD

**Issue by whuxujiyuan** [plutinosoft/Platinum#35]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/1314078/97269500-93301780-1868-11eb-907c-fa371c75c7c1.png">

**Comment by c0diq** [comment]
Could you try the [neptune-3](https://github.com/plutinosoft/Platinum/tree/neptunre-1.3) branch please and see if that works better for you? I have updated axTLS to a newer version.
