### ISSUE TITLE
windows media player play error

### ISSUE THREAD

**Issue by zqfoffice** [plutinosoft/Platinum#42]
hello,why use windows media player connect mediarendertest show anomalies。The contact surface following chart shows，how to recover the error?
![1](https://user-images.githubusercontent.com/22447561/147207062-41db5495-402e-4bc6-998c-f6cb11672e71.jpg)

**Comment by c0diq** [comment]
MediaRenderTest is not hooked up to a media playback engine. It only shows how to receive commands over UPnP.
